
build:
  image: node:5.10
  commands:
    - npm install
    - npm run lint
    - npm run test
    - npm run clean
    - npm run build
notify:
  slack:
    webhook_url: https://hooks.slack.com/services/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
    when:
      success: true
      failure: true
      change: true