build:
  image: node:5.10
  commands:
    - npm install cnpm -g --registry=https://registry.npm.taobao.org
    - cnpm install
    - npm run lint
    - npm run test
    - npm run clean
    - npm run build
