export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const EXTEND_CONTEXT = 'EXTEND_CONTEXT';
export const SELECT_SERVICE = 'SELECT_SERVICE';

export const SET_FOLDER_LOCATION = 'SET_FOLDER_LOCATION';
export const REMOVE_FOLDER_LOCATION = 'REMOVE_FOLDER_LOCATION';
